# Generated by Django 5.1.4 on 2025-06-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_rubrique_slug_alter_sousrubrique_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrique',
            name='powerbi_url',
            field=models.URLField(blank=True, help_text='Lien vers le rapport Power BI pour cette rubrique', null=True),
        ),
        migrations.AddField(
            model_name='sousrubrique',
            name='powerbi_url',
            field=models.URLField(blank=True, help_text='Lien vers le rapport Power BI pour cette sous-rubrique', null=True),
        ),
    ]
